# Generated by Django 2.2.3 on 2019-08-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beapi', '0002_centre_jobstatus_jobtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appflow',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
                ('appflow_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('section', models.CharField(blank=True, max_length=100, null=True)),
                ('app', models.CharField(blank=True, max_length=50, null=True)),
                ('workflow_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'appflow',
                'managed': False,
            },
        ),
    ]
