# Generated by Django 2.2.3 on 2019-08-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beapi', '0003_appflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamLeader',
            fields=[
                ('team_leader', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('specialisation', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
                ('team_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('team_leader', models.CharField(blank=True, max_length=100, null=True)),
                ('team_member', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
