# Generated by Django 2.2.3 on 2019-08-19 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beapi', '0004_auto_20190819_1058'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamMember',
            new_name='Team',
        ),
    ]
