# Generated by Django 2.2.3 on 2019-08-19 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beapi', '0005_auto_20190819_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_leader',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='beapi.TeamLeader'),
            preserve_default=False,
        ),
    ]
