# Generated by Django 2.2.3 on 2019-08-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beapi', '0007_auto_20190820_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_username', models.CharField(blank=True, max_length=100, null=True)),
                ('client_message', models.CharField(blank=True, max_length=100, null=True)),
                ('client_socket', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'client_data',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='team',
            table='team',
        ),
        migrations.AlterModelTable(
            name='teamleader',
            table='teamleader',
        ),
    ]
