# Generated by Django 2.2.3 on 2019-08-27 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beapi', '0008_auto_20190827_1242'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientData',
        ),
    ]
