# Generated by Django 2.2.3 on 2019-09-02 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beapi', '0009_delete_clientdata'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jobstatus',
            table='jobstatus',
        ),
        migrations.AlterModelTable(
            name='jobtype',
            table='jobtype',
        ),
    ]
