# Generated by Django 2.2.3 on 2019-10-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beapi', '0010_auto_20190902_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('profile_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dt_created', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roleprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('dt_created', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roleprofile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sectiongroup',
            fields=[
                ('section', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('grp', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sectiongroup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('section', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'userprofile',
                'managed': False,
            },
        ),
    ]
