# Generated by Django 2.2.3 on 2019-10-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beapi', '0011_profile_roleprofile_sectiongroup_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobWorkflowStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_code', models.CharField(blank=True, max_length=100, null=True)),
                ('section', models.CharField(blank=True, max_length=100, null=True)),
                ('responsible', models.CharField(blank=True, max_length=100, null=True)),
                ('ec_num', models.CharField(blank=True, max_length=100, null=True)),
                ('action', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'job_workflow_status',
                'managed': False,
            },
        ),
    ]
