# Generated by Django 2.2.3 on 2019-12-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beapi', '0012_jobworkflowstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobFormsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('assignee', models.CharField(blank=True, max_length=100, null=True)),
                ('decision', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'zdforms',
                'managed': False,
            },
        ),
    ]
