# Generated by Django 2.2 on 2021-09-17 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beweb', '0004_auto_20190927_0857'),
    ]

    operations = [  ]
